Story 13
ericdrosado/Hangman-App pull request #3
Opened 2017-06-13 22:22 UTC by ericdrosado

2017-06-14 14:44 UTC, NicoleCarpenter requested changes

2017-06-14 14:44 UTC, NicoleCarpenter commented on game.rb
> +    while @validator.is_a_word?(@word=(@io_handler.get_input.upcase)) == false
`x == false` should be `!x`

2017-06-14 14:44 UTC, NicoleCarpenter commented on game.rb
>    def game_handler
Your method names should be verbs. This would probably be more understandable as something like `play_game`

2017-06-14 14:44 UTC, NicoleCarpenter commented on game.rb
> +    system "clear"
I am curious about how you would be able to test this method without actually clearing the console... Were you having that problem?

2017-06-14 14:44 UTC, NicoleCarpenter commented on game.rb
> +    while @validator.is_a_word?(@word=(@io_handler.get_input.upcase)) == false
This functionality does not belong in your game loop. Your game loop should not be validating word choice, it should only take a valid word and play the game.

2017-06-14 14:44 UTC, NicoleCarpenter commented on game.rb
> +    while @validator.is_a_letter?(@letter=(@io_handler.get_input.downcase)) == false
This functionality should not be in the game loop.

2017-06-14 14:44 UTC, NicoleCarpenter commented on spec/game_spec.rb
> +  describe '#game_handler' do
This is a good test for the most part, but it is limited in that it does not actually test the main functionality of the game. You are testing the side effects, which is good, but this does not prove that you can play a game of hangman.

When we have game ending conditions in place, we will have to revisit these tests.

2017-06-14 14:44 UTC, NicoleCarpenter commented on spec/game_view_spec.rb
> +    it 'will blank uppercase letters T and S' do
Interesting way of handling this

2017-06-14 14:44 UTC, NicoleCarpenter commented on validator.rb
> +  def is_a_letter? letter
See above comment.

2017-06-14 14:44 UTC, NicoleCarpenter commented on validator.rb
> +  def is_a_word? word
This if/else is unnecessary, `word.match(/^[a-zA-Z]+$/) && word.length > 1` by itself will either return as true or false.

2017-06-14 14:48 UTC, tommcgee commented on game.rb
> +    while @validator.is_a_word?(@word=(@io_handler.get_input.upcase)) == false
This line seems like too much is going on

2017-06-14 14:49 UTC, tommcgee commented on spec/game_spec.rb
> +  describe '#game_handler' do
+1

2017-06-14 14:54 UTC, ericdrosado commented on validator.rb
> +  def is_a_word? word
I tried that originally and it didn't work. I thought it was strange, so I decided just to move on and blow it out.

2017-06-14 16:54 UTC, tommcgee commented on spec/game_view_spec.rb
> +    it 'will blank uppercase letters T and S' do
Cool idea :+1:

2017-06-15 14:46 UTC, NicoleCarpenter requested changes

2017-06-15 14:46 UTC, NicoleCarpenter commented on game.rb
> +    @word = @validator.validate_selection(@prompter.prompt_for_word, 'is_a_word?')
Why are these variables not local? You should be passing these variables around when you need them rather than making them available over wider scopes

2017-06-15 14:46 UTC, NicoleCarpenter commented on game.rb
> +    @io_handler.printer(@prompter.prompt_for_letter)
Just on that same note as `play_game`, all of these methods should be verbs please

2017-06-15 14:46 UTC, NicoleCarpenter commented on game.rb
> +    @word = @validator.validate_selection(@prompter.prompt_for_word, 'is_a_word?')
Good job removing that validation logic

2017-06-15 14:46 UTC, NicoleCarpenter commented on game_start.rb
> +validator = Validator.new(prompter, io_handler)
👍

2017-06-15 14:46 UTC, NicoleCarpenter commented on game_view.rb
> +  def clear_view
👍

2017-06-15 14:46 UTC, NicoleCarpenter commented on spec/game_spec.rb
> +  describe '#game_handler' do
You are describing `#play_game` now ;-)

Also, same note as before applies, but we can come back to this later (testing side effects 👍 testing main effect 👎 )

2017-06-15 14:46 UTC, NicoleCarpenter commented on validator.rb
> +    !! word.match(/^[a-zA-Z]+$/) && word.length > 1
🆒

2017-06-15 14:46 UTC, NicoleCarpenter commented on validator.rb
> +  def validate_selection prompt, validation_type
interesting...

2017-06-15 15:49 UTC, NicoleCarpenter approved these changes

2017-06-15 15:52 UTC, tommcgee approved these changes

2017-06-15 15:53 UTC, merged